// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
<<<<<<< HEAD
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
=======
      return web;
>>>>>>> 624b808 (fixed(july31))
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
<<<<<<< HEAD
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
=======
        return macos;
>>>>>>> 624b808 (fixed(july31))
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

<<<<<<< HEAD
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA7CXiC2SA3a4y8mZNljvzvdD1Aber4GM',
    appId: '1:481798215371:android:b6f4490561967dcb51ed4e',
=======
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX82XgPZoqDJN4Xzc4Ty1SCQsDjRTATas',
    appId: '1:481798215371:web:1948b97a10ea128051ed4e',
    messagingSenderId: '481798215371',
    projectId: 'u-traffic',
    authDomain: 'u-traffic.firebaseapp.com',
    storageBucket: 'u-traffic.appspot.com',
    measurementId: 'G-TWLSVQ2YPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA7CXiC2SA3a4y8mZNljvzvdD1Aber4GM',
    appId: '1:481798215371:android:7deca3581c0bab7d51ed4e',
>>>>>>> 624b808 (fixed(july31))
    messagingSenderId: '481798215371',
    projectId: 'u-traffic',
    storageBucket: 'u-traffic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFFTvFbJQTdCLLvf93R8TYME-VmfOhW0w',
<<<<<<< HEAD
    appId: '1:481798215371:ios:747a21922e6728c451ed4e',
=======
    appId: '1:481798215371:ios:8ab8e0f7c17de3a051ed4e',
>>>>>>> 624b808 (fixed(july31))
    messagingSenderId: '481798215371',
    projectId: 'u-traffic',
    storageBucket: 'u-traffic.appspot.com',
    iosClientId:
<<<<<<< HEAD
        '481798215371-ttiur776lo7hvce4rlvjd3rvf3mfmfo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.uTrafficDriver',
=======
        '481798215371-ngfr6otb1p8fk3qg9vvh6im4fvbb51e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverslogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFFTvFbJQTdCLLvf93R8TYME-VmfOhW0w',
    appId: '1:481798215371:ios:8ab8e0f7c17de3a051ed4e',
    messagingSenderId: '481798215371',
    projectId: 'u-traffic',
    storageBucket: 'u-traffic.appspot.com',
    iosClientId:
        '481798215371-ngfr6otb1p8fk3qg9vvh6im4fvbb51e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverslogin',
>>>>>>> 624b808 (fixed(july31))
  );
}
